name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'benchmark'
            exclude: '' # Nothing to exclude
          - check: 'library'
            exclude: '' # Nothing to exclude
          - check: 'test'
            exclude: '' # Nothing to exclude
          - check: 'tools'
            exclude: '' # Nothing to exclude
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'LLVM' # optional
